import pandas as pd
import yfinance as yf
from typing import Optional
from max_config import MaxConfig

class MaxDataEngine:
    """Handles fetching historical data and generating technical indicators."""
    
    def __init__(self):
        self.config = MaxConfig()

    def fetch_data(self, ticker: str) -> Optional[pd.DataFrame]:
        """Fetches historical market data using yfinance API."""
        try:
            # Fetch approx history
            period = f"{self.config.HISTORY_YEARS}y"
            df = yf.download(ticker, period=period, progress=False)
            if df.empty:
                return None
            
            # Robust MultiIndex cleanup to prevent extraction failures in Streamlit Cloud
            if isinstance(df.columns, pd.MultiIndex):
                # Flattens tiered columns like ('Close', 'AAPL') down to just 'Close'
                df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

            return df
        except Exception as e:
            raise RuntimeError(f"Data Fetch Error: {e}")

    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Computes and appends technical indicators to the DataFrame."""
        df = df.copy()
        
        # Extract 'Close' safely as a single dimensional Series for indicators
        if 'Close' not in df.columns:
            raise KeyError("The fetched DataFrame does not contain a valid 'Close' column.")
            
        close = df['Close']
        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]
            
        # Simple Moving Average
        df['SMA'] = close.rolling(window=self.config.SMA_WINDOW).mean()
        
        # Exponential Moving Average
        df['EMA'] = close.ewm(span=self.config.EMA_WINDOW, adjust=False).mean()
        
        # Relative Strength Index (RSI)
        delta = close.diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=self.config.RSI_WINDOW).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=self.config.RSI_WINDOW).mean()
        
        # Prevent division by zero errors during flat market sessions
        loss = loss.replace(0, 0.00001)
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))
        
        # Target: Next Day's Close Price
        df['Target'] = close.shift(-1)
        
        # Clear out empty rows generated by moving average windows and target shifting
        df = df.dropna(subset=['SMA', 'EMA', 'RSI', 'Target'])
        
        return df
