import pandas as pd
import yfinance as yf
from typing import Optional
from max_config import MaxConfig

class MaxDataEngine:
    """Handles fetching historical data and generating technical indicators."""
    
    def __init__(self):
        self.config = MaxConfig()

    def fetch_data(self, ticker: str) -> Optional[pd.DataFrame]:
        """Fetches historical market data using yfinance API."""
        try:
            # Fetch approx history
            period = f"{self.config.HISTORY_YEARS}y"
            df = yf.download(ticker, period=period, progress=False)
            if df.empty:
                return None
            
            # Clean dataframe multi-index if yfinance returns it
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)

            return df
        except Exception as e:
            # We don't print to console here as the Orchestrator will handle logging
            raise RuntimeError(f"Data Fetch Error: {e}")

    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Computes and appends technical indicators to the DataFrame."""
        df = df.copy()
        
        # Extract 'Close' as Series for cleaner computations
        if isinstance(df['Close'], pd.DataFrame):
            close = df['Close'].iloc[:, 0]
        else:
            close = df['Close']
            
        # Simple Moving Average
        df['SMA'] = close.rolling(window=self.config.SMA_WINDOW).mean()
        
        # Exponential Moving Average
        df['EMA'] = close.ewm(span=self.config.EMA_WINDOW, adjust=False).mean()
        
        # Relative Strength Index (RSI)
        delta = close.diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=self.config.RSI_WINDOW).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=self.config.RSI_WINDOW).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))
        
        # Target: Next Day's Close Price
        df['Target'] = close.shift(-1)
        
        # Drop missing values generated by indicators
        df.dropna(inplace=True)
        return df
